name: Deploy Laravel + Vite (Self-Hosted)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: /var/www/html/AppZoneVaz

    steps:
      - name: Grant full permissions to fanzone
        run:  chmod -R 777 /home/emsthias33/actions-runner/fanzone/

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Backup .env before deleting
        run: cp /var/www/html/AppZoneVaz/.env /tmp/.env_backup

      - name: Delete everything in AppZoneVaz except .env
        run:  rm -rf /var/www/html/AppZoneVaz/* 

      - name: Move new files from fanzone to AppZoneVaz
        run:  cp -r /home/emsthias33/actions-runner/fanzone/fanzone/fanzone/* /var/www/html/AppZoneVaz/

      - name: Restore .env file
        run: cp /tmp/.env_backup /var/www/html/AppZoneVaz/.env

      - name: Set permissions
        run:  chmod -R 777 /var/www/html/AppZoneVaz/

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Set Laravel writable folders
        run:  chmod -R 777 storage bootstrap/cache

      - name: Install Node.js dependencies
        run: npm install

      - name: Build Vite assets
        run: npm run build

      - name: Final permissions fix
        run:  chmod -R 777 /var/www/html/AppZoneVaz/