name: Deploy Laravel + Vite (Self-Hosted)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: /var/www/html/AppZoneVaz

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy .env to new location (runs before delete)
        run: cp /var/www/html/AppZoneVaz/.env /home/emsthias33/actions-runner/fanzone/fanzone/fanzone/.env

      - name: grant permissions
        run: cd /var/www/html/AppZoneVaz/ && sudo chmod -R 777 ./

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Set file permissions
        run: sudo chmod -R 777 storage bootstrap/cache

      - name: Install Node.js dependencies
        run: npm install && sudo chmod -R 777 node_modules

      - name: grant permissions
        run: cd /var/www/html/AppZoneVaz/ && sudo chmod -R 777 ./

      - name: Build Vite assets
        run: npm run build

      - name: grant permissions
        run: cd /var/www/html/AppZoneVaz/ && sudo chmod -R 777 ./

      - name: Move Vite manifest.json
        run: cp public/build/.vite/manifest.json public/build/

      - name: Run Laravel migrations
        run: php artisan migrate --force

      - name: Copy .env to new location (runs before delete)
        run: cp /var/www/html/AppZoneVaz/.env /home/emsthias33/actions-runner/fanzone/fanzone/fanzone/.env

      - name: Delete all files inside /var/www/html/AppZoneVaz/
        run: sudo rm -rf /var/www/html/AppZoneVaz/*

      - name: Copy all files (except .env) to /var/www/html/AppZoneVaz
        run: sudo cp -r /home/emsthias33/actions-runner/fanzone/fanzone/fanzone/* /var/www/html/AppZoneVaz/

      - name: grant permissions
        run: cd /var/www/html/AppZoneVaz/ && sudo chmod -R 777 ./